### ISSUE TITLE
Problem with version 1.1.0

### ISSUE THREAD

**Issue by AndreyShpilevoy** [milesj/aesthetic#10]
Hi, I have error
`ERROR in ./~/aesthetic/index.js
Module not found: Error: Can't resolve './lib/Aesthetic' in 'C:\Git\dem-afterlife\src\dem-afterlife-ui\node_modules\aesthetic'
 @ ./~/aesthetic/index.js 8:18-44
 @ multi babel-polyfill aesthetic aesthetic-adapter-jss history jss jss-camel-case jss-default-unit jss-expand jss-extend jss-nested jss-props-sort jss-vendor-prefixer raven-js react react-dom re
act-notification-system react-redux react-router react-router-redux redux redux-saga webpack-hot-middleware/client?reload=true`

As I see - node_modules\aesthetic is hadn't folder Lib and all necessary files.
Please, can you check it?

**Comment by milesj** [comment]
What packages are you using?
