### ISSUE TITLE
How do you access the react props from the styler function?

### ISSUE THREAD

**Issue by cuevash** [milesj/aesthetic#12]
Typically in a code like:

style((theme) => ({
  button: {
    fontSize: `${theme.unitSize}${theme.unit}`,
    fontFamily: theme.font,
    padding: theme.spacing,
  },
}))(Component);

you has access to the theme object, but how can you access the props object that is passed to the HoC ?

Cheers!

**Comment by milesj** [comment]
Hey @cuevash,

The React props are not passed to the style function, only the theme and any parent styles. What use case do you have for needing the props?

**Comment by milesj** [comment]
@cuevash 

This is now possible with 2.0. https://github.com/milesj/aesthetic#style-functions
