### ISSUE TITLE
[Question] Can the `stylename` be part of a component's classnames?

### ISSUE THREAD

**Issue by alanbuchanan** [milesj/aesthetic#22]
We are using aesthetic with JSS in our project.

Here is an excerpt of our rendered HTML:
`<a class="logo-0-1-9"><div class="image-0-1-7"></div></a>`

Is it possible to have the stylename included as part of the classname, for example:

`<a class="MyComponent__logo-0-1-9"><div class="MyImage__image-0-1-7"></div></a>`

**Comment by milesj** [comment]
Hah, it was actually this way in Aesthetic 1.0, but was removed during the rewrite. I can easily add it back in. 👍

**Comment by milesj** [comment]
Should work now in 2.1!
