### ISSUE TITLE
IE 11+

### ISSUE THREAD

**Issue by loganpowell** [milesj/aesthetic#25]
Reeeeeallly want to try this. Is the IE 11+ support a matter of test coverage (i.e., a soft-requirement) or a hard requirement (i.e., it will not work.)?

**Comment by milesj** [comment]
It's how babel is transpiled. I actually target IE10 (as seen here: https://github.com/milesj/build-tool-config/blob/master/configs/babel.js#L27), so it really depends on what needs polyfilled or just is broken.

**Comment by loganpowell** [comment]
Would it be hugely difficult to get parity with React (i.e., IE 9)?

**Comment by milesj** [comment]
Have you tried using Aesthetic in IE9? I'm curious what's actually broken. I'm sure it's stuff like missing Set/Map.

That being said, I'm not really looking into support IE9 and any bugs involved with it.

**Comment by loganpowell** [comment]
I'm just comparison shopping at the moment, but I'm in government, so we have to support these ancient things :sob: Thank you for following up!

**Comment by milesj** [comment]
No worries, thanks for the interest!
