### ISSUE TITLE
Backslash in pseudo element content.

### ISSUE THREAD

**Issue by jacksenior** [milesj/aesthetic#26]
Using unicode characters for the content of a pseudo element from within a custom font.

In the bellow the `\` gets stripped out by jss in both.
```
 content: '"\e000"',
 content: '"/\e000"',
```

Leaving me with either 
```
  content: "e000";
  content: "/e000";
```
Is it possible to escape these, If so what am I missing?

**Comment by milesj** [comment]
Are you using unified syntax? Can you try a double slash, like `\\`?

Can you else send me your JSS setup so I can test a bit.

**Comment by jacksenior** [comment]
That worked awesome thanks.

**Comment by milesj** [comment]
Awesome, thanks!
