### ISSUE TITLE
Referencing the component inside the styler wrapper

### ISSUE THREAD

**Issue by jacksenior** [milesj/aesthetic#28]
```              
<Comp
  ref={ref => this.name = ref}
/>
```

The above used to give access to the functions and methods contained on that component. Now that component is wrapped in a styled component we are ferencing the styler. I've managed to pass refs through and reference specific dom nodes but can't get the original Component.

Pretty sure its accomplishable I just can't figure it out. any solution appreciated

**Comment by jacksenior** [comment]
Fixed by passing an innerRef prop and running in constructor of the child component.
```
    this.props.innerRef(this)
```

**Comment by milesj** [comment]
Glad you got something working. That being said, I should probably support this first-class, similar to how Redux `connect()` does. I'll leave this open for now.

**Comment by milesj** [comment]
Just added a `wrappedRef` prop to get the underlying component instance.
