### ISSUE TITLE
CID return from className generator

### ISSUE THREAD

**Issue by jacksenior** [milesj/aesthetic#29]
The cid generator in src/style.js can generate random strings that start with numbers.
classNames that start with numbers are ignored by the browser so when trying to user version 2.0+ on our prod environment styles get applied or not applied at random depending on whether the generator made a CID starting with a letter.

I tried to submit a pr to change the line to  
`c${Math.random().toString(32).substr(2)}${instanceID}`

to force it to always start with a c. I get permission denied when I try to push my branch though?

**Comment by prependto** [comment]
+1

**Comment by designalchemy** [comment]
https://github.com/milesj/aesthetic/pull/30

**Comment by milesj** [comment]
Thanks for the report and for the fix!
