### ISSUE TITLE
Production ready? Or when?

### ISSUE THREAD

**Issue by maotora** [milesj/aesthetic#3]
Hi!

Awesome library man!

Can I use it in a production application? Or, like, when will it be ready?

It kinda looks ready but I still see rapid development going on.

Thanks!

**Comment by milesj** [comment]
Hey @maotora! I'm not sure about production ready (I haven't used it in prod yet), but it's definitely usable. However, I definitely suggest trying it out and reporting back any issues!

I just tagged v0.3.0 which should be considered "final". The only thing I have left to figure out is possible React Native support.

**Comment by maotora** [comment]
Awesome man!

Well I'll do that. But also one more thing, why are you not watching this repo?
Like it has `0 watch` which makes support handling pretty late, I would love to watch if i could solve an issue but then i'm only a user man.

Cheers!

**Comment by milesj** [comment]
Woah, thanks for pointing that out. I assumed GH would auto-watch me on my own repositories...

**Comment by maotora** [comment]
Np, Thanks man!
