### ISSUE TITLE
Multiple external stylesheet imports.

### ISSUE THREAD

**Issue by jacksenior** [milesj/aesthetic#34]
Jss supports multiple imports via an array of strings, https://github.com/cssinjs/jss/issues/230

```
    '@import': [
      'react-date-range/dist/styles.css',
      'react-date-range/dist/theme/default.css',
    ],
```

aesthetic throws `error @import value must be string`
I can work around this by importing the two files in separate style objects or by combining them in an external css file.

**Comment by milesj** [comment]
This should be supported in the next version.
